import { StyleSheet } from "react-native";


export const modalStyles = StyleSheet.create({
    modalButtonContainer: {
      display: "flex",
      flexDirection: "row",
      width: "100%",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
      height: "10%",
    },
    modalTabButton: {
      margin: 5,
      flex: 1,
      padding: 1,
      borderWidth: 1,
      borderRadius: 10,
      borderColor: "#d6d6d6",
      backgroundColor: "white",
      height: 30,
      fontSize: 20,
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
    },
    modalTabButtonActive: {
      margin: 5,
      flex: 1,
      padding: 1,
      borderWidth: 2,
      borderRadius: 10,
      borderColor: "#47a68d",
      backgroundColor: "white",
      height: 30,
      fontSize: 20,
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
    },
    modalTabButtonText: {
      color: "grey",
      fontSize: 15,
    },
    closeModalButtonContainer: {
      width: "90%",
      height: 40,
      display: "flex",
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      textAlign: "center",
      alignContent: "center",
      borderRadius: 10,
      backgroundColor: "#47a68d",
      marginTop: 10,
    },
  
    closeModalButton: {
      color: "white",
      fontSize: 15,
      fontFamily: "Nunito_400Regular",
    },
    scrollBorder: {
      borderBottomWidth: 1,
      borderBottomColor: "#d6d6d6",
      borderTopWidth: 1,
      borderTopColor: "#d6d6d6",
    },
    outerModalContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    innerModalContainer: {
      height: "98%",
      width: "98%",
      padding: "5%",
      backgroundColor: "white",
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
      alignItems: "center",
      textAlign: "center",
      borderWidth: 1,
      borderRadius: 10,
      borderColor: "#d6d6d6",
    },
    modalTitle: {
      fontSize: 15,
      color: "grey",
      marginBottom: 10,
    },
    modalSubTitle: {
      fontSize: 20,
      fontWeight: "bold",
      color: "grey",
      marginTop: 10,
      marginBottom: 10,
    },
    modalText: {
      flex: 1,
      fontSize: 15,
      color: "grey",
    },
    buttonContainerPressed: {
      width: "90%",
      height: 40,
      display: "flex",
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      textAlign: "center",
      alignContent: "center",
      borderRadius: 10,
      backgroundColor: "#245448",
    },
  });